### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by kegan-cunningham** [kegan-cunningham/Starsurfing#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by m1010j** [comment]
Make sure to have a demo login!

**Comment by TheSlyPig** [comment]
Done!

**Comment by m1010j** [comment]
👍
