### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by m1010j** [kegan-cunningham/Starsurfing#2]
Looks great already! Some comments:
- [x] I'm getting a 500 error after signing up. This might be because you made some local migration but haven't migrated on heroku yet. If so, try `heroku run bundle exec rake db:migrate`.
- [x] The fonts for the form input fields could use some work.
- [x] Your session form should be a modal, just like on the site you're cloning.

**Comment by TheSlyPig** [comment]
Thanks! All issues should be resolved.

**Comment by m1010j** [comment]
Looks great!
