### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by m1010j** [kegan-cunningham/Starsurfing#7]
- [x] You should have `cursor: pointer` when you hover over a star in your star index and when you hover over a user in your star show.

- [x] When I try to leave a review for a user without being logged in, I should get redirected to the splash page with the login modal open already.

- [x] You should render errors for your review form.

**Comment by TheSlyPig** [comment]
Cursors are fixed.

I simply removed the "Leave a review button" for users who aren't logged in.

Review errors are now a thing! Thanks for the help.
